-- SecChat schema design for the future PgStore (src/store/ — NOT YET IMPLEMENTED).
--
-- This migration is NOT applied by anything today: the running system is entirely the
-- in-memory MemoryStore (src/store/memory.ts). It exists so a Postgres-backed Store
-- implementation has an agreed-on shape to build against, and so the durable schema can be
-- reviewed now, while it is still cheap to change.
--
-- Mirrors src/types.ts (Channel, Member, Message, AuditEvent) directly, plus a `workspaces`
-- table for Channel.workspaceId — which has NO formal TS contract yet (see the note on that
-- table below; this is flagged in the task report as a real gap, not glossed over here).
--
-- Append-only intent (decision #9: tamper-evident chains, but CUI must stay purgeable):
--   * messages        — INSERT-only, plus exactly ONE allowed UPDATE shape: redactMessage()
--                        stamping redacted_at (NULL -> timestamp, one-way, and nothing else on
--                        the row may change — see messages_guard_update() below). DELETE is
--                        always blocked. This is what lets a redaction tombstone a row without
--                        ever touching the chain-bound columns (content_sha256/prev_hash/hash).
--   * message_content  — the OPPOSITE: this table is meant to be deleted from. Plaintext lives
--                        ONLY here, one row per (unredacted) message. redactMessage() = DELETE
--                        FROM message_content WHERE message_id = ...; the messages row (and the
--                        hash chain, which binds content_sha256 rather than the plaintext) is
--                        untouched, so the chain still verifies after redaction.
--   * audit_log       — fully immutable: no UPDATE, no DELETE, ever. There is no "un-audit."
--
-- Enforcement is layered, deliberately NOT just REVOKE/GRANT:
--   1. BEFORE UPDATE/DELETE triggers are the real guarantee — they fire regardless of who owns
--      the table. Plain GRANT/REVOKE alone is NOT sufficient here because a table's OWNER
--      bypasses ordinary privilege checks entirely, and it's easy for an app to end up
--      connecting as the owner role in smaller deployments.
--   2. REVOKE/GRANT is added on top as declared intent + defense-in-depth for any non-owner
--      role. A least-privilege app role (rather than connecting as owner) should be introduced
--      in a later migration once PgStore actually lands; until then these grants target PUBLIC.
--
-- IDs and timestamps are supplied by the application (crypto.randomUUID(), new
-- Date().toISOString()), the same way MemoryStore does it — not generated by the database — so
-- there are no DEFAULT expressions for `id`/timestamp columns and no uuid-generation extension
-- dependency (kept consistent with the "dependencies are a liability" policy in README.md).

BEGIN;

-- ---------------------------------------------------------------------------------------------
-- workspaces
--
-- NOT YET a formal contract: src/types.ts defines Channel.workspaceId but exports no
-- `Workspace` interface, and the Store port has no createWorkspace/getWorkspace methods.
-- MemoryStore therefore does no workspace bookkeeping at all today — workspaceId is just an
-- opaque string on Channel. This table is a minimal, obvious-columns-only placeholder so
-- channels.workspace_id has something to reference; revisit once a Workspace contract lands in
-- src/types.ts (flagged in the task report).
-- ---------------------------------------------------------------------------------------------
CREATE TABLE workspaces (
  id         uuid PRIMARY KEY,
  name       text NOT NULL,
  created_by text NOT NULL,             -- Principal.sub — see note on channels.created_by below
  created_at timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------------------------
-- channels — mirrors src/types.ts Channel
-- ---------------------------------------------------------------------------------------------
CREATE TABLE channels (
  id           uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces (id) ON DELETE RESTRICT,
  kind         text NOT NULL CHECK (kind IN ('human', 'agent', 'dm')),
  name         text,                    -- Channel.name?
  cui_marking  text,                    -- Channel.cuiMarking?, e.g. "CUI//SP-PRVCY" (32 CFR 2002)
  -- Principal.sub of the creator. Deliberately NOT a foreign key: SecChat has no local users
  -- table by design (README: "SSO from the ground up") — identity lives in the IdP and is
  -- verified via JWKS on every request (src/auth/), never mirrored locally.
  created_by   text NOT NULL,
  created_at   timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------------------------
-- agents — mirrors src/types.ts Agent. Owned by (and acting as) exactly one user; joins its
-- channels as a member (see channel_members.member_type = 'agent'). No local users FK by design.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE agents (
  id         uuid PRIMARY KEY,
  owner_sub  text NOT NULL,            -- Principal.sub the agent is tied to and acts as; no FK
  kind       text NOT NULL CHECK (kind IN ('assistant', 'coding')),
  name       text,                     -- Agent.name?
  model      text,                     -- Agent.model? — SecRouter model id (assistant path)
  created_at timestamptz NOT NULL
);

CREATE INDEX agents_owner_sub_idx ON agents (owner_sub);  -- backs listAgentsByOwner()

-- ---------------------------------------------------------------------------------------------
-- channel_members — mirrors src/types.ts Member
-- ---------------------------------------------------------------------------------------------
CREATE TABLE channel_members (
  channel_id  uuid NOT NULL REFERENCES channels (id) ON DELETE RESTRICT,
  member_ref  text NOT NULL,            -- Principal.sub (user) or agent id (agent); no local FK
  member_type text NOT NULL CHECK (member_type IN ('user', 'agent')),
  role        text NOT NULL CHECK (role IN ('owner', 'member')),
  PRIMARY KEY (channel_id, member_ref)
);

-- Inverse-direction lookup ("which channels is this ref a member of"); channel_id-first lookups
-- (isMember/listMembers) are already covered by the primary key above.
CREATE INDEX channel_members_member_ref_idx ON channel_members (member_ref);

-- ---------------------------------------------------------------------------------------------
-- messages — mirrors src/types.ts Message. Append-only; see header comment.
--
-- content_sha256/prev_hash/hash are exactly the fields src/audit/chain.ts binds into the hash
-- (computeMessageHash) — they must never change after insert, redaction included. Plaintext is
-- NOT a column here; see message_content.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE messages (
  id             uuid PRIMARY KEY,
  channel_id     uuid NOT NULL REFERENCES channels (id) ON DELETE RESTRICT,
  seq            integer NOT NULL CHECK (seq > 0),
  author_ref     text NOT NULL,         -- Principal.sub or agent id; no local FK (see channels)
  author_type    text NOT NULL CHECK (author_type IN ('user', 'agent')),
  prompted_by    text,                  -- Message.promptedBy? — human who triggered an agent turn
                                        -- (provenance; set at insert, NOT bound into the hash chain)
  content_sha256 text NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
  prev_hash      text NOT NULL CHECK (prev_hash ~ '^[0-9a-f]{64}$'),
  hash           text NOT NULL CHECK (hash ~ '^[0-9a-f]{64}$'),
  created_at     timestamptz NOT NULL,
  redacted_at    timestamptz,           -- Message.redactedAt? — one-way tombstone, unset by default
  -- Enforces the 1-based, gapless-per-channel sequence and doubles as the index that backs
  -- listMessages()'s "seq order" query.
  UNIQUE (channel_id, seq)
);

REVOKE DELETE, UPDATE ON messages FROM PUBLIC;
GRANT UPDATE (redacted_at) ON messages TO PUBLIC;   -- the one column redactMessage() may touch

CREATE OR REPLACE FUNCTION messages_block_delete() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'messages is append-only: DELETE is not permitted (id=%)', OLD.id;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER messages_no_delete
  BEFORE DELETE ON messages
  FOR EACH ROW EXECUTE FUNCTION messages_block_delete();

-- The real enforcement for "only redacted_at, and only NULL -> timestamp, ever": the
-- column-level GRANT above helps document intent, but a table OWNER bypasses privilege checks
-- entirely, so it can't be trusted alone. Every chain-bound field must stay byte-identical to
-- OLD, or src/audit/chain.ts's verifyMessageChain would stop matching what's stored; redacted_at
-- itself is a one-way tombstone (no "un-redact").
CREATE OR REPLACE FUNCTION messages_guard_update() RETURNS trigger AS $$
BEGIN
  IF NEW.id             IS DISTINCT FROM OLD.id
     OR NEW.channel_id     IS DISTINCT FROM OLD.channel_id
     OR NEW.seq            IS DISTINCT FROM OLD.seq
     OR NEW.author_ref     IS DISTINCT FROM OLD.author_ref
     OR NEW.author_type    IS DISTINCT FROM OLD.author_type
     OR NEW.prompted_by    IS DISTINCT FROM OLD.prompted_by
     OR NEW.content_sha256 IS DISTINCT FROM OLD.content_sha256
     OR NEW.prev_hash      IS DISTINCT FROM OLD.prev_hash
     OR NEW.hash           IS DISTINCT FROM OLD.hash
     OR NEW.created_at     IS DISTINCT FROM OLD.created_at
  THEN
    RAISE EXCEPTION 'messages is append-only: only redacted_at may change (id=%)', OLD.id;
  END IF;

  IF OLD.redacted_at IS NOT NULL AND NEW.redacted_at IS DISTINCT FROM OLD.redacted_at THEN
    RAISE EXCEPTION 'messages.redacted_at is a one-way tombstone (id=%)', OLD.id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER messages_guard_update
  BEFORE UPDATE ON messages
  FOR EACH ROW EXECUTE FUNCTION messages_guard_update();

-- ---------------------------------------------------------------------------------------------
-- message_content — plaintext, split out so redaction can delete it without touching messages.
--
-- One row per (unredacted) message. redactMessage(id, ...) = DELETE FROM message_content WHERE
-- message_id = id, full stop — no trigger guards this table; deletion is the intended operation.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE message_content (
  -- ON DELETE CASCADE is moot today (messages can never be deleted — see the trigger above) but
  -- documents intent if that ever changes.
  message_id uuid PRIMARY KEY REFERENCES messages (id) ON DELETE CASCADE,
  content    text NOT NULL
);

-- ---------------------------------------------------------------------------------------------
-- audit_log — mirrors src/types.ts AuditEvent. The global, metadata-only chain (never content —
-- see src/audit/chain.ts header). Fully immutable once inserted.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE audit_log (
  id        uuid PRIMARY KEY,
  seq       integer NOT NULL CHECK (seq > 0) UNIQUE,  -- one global sequence, not per-channel
  actor     text NOT NULL,             -- Principal.sub or service id; no local FK
  act_as    text,                      -- AuditEvent.actAs? — delegated end-user
  action    text NOT NULL,             -- e.g. "message.redact", "channel.create"
  -- Deliberately NOT a foreign key: target can point at a message, a channel, or any future
  -- entity kind — a loose reference by design, matching the "metadata-only" audit philosophy
  -- (this table doesn't get to assume what it's an audit trail FOR).
  target    text,
  detail    text,                      -- AuditEvent.detail? — short metadata note (e.g. a
                                        -- redaction reason). Metadata only — NEVER CUI content.
  prev_hash text NOT NULL CHECK (prev_hash ~ '^[0-9a-f]{64}$'),
  hash      text NOT NULL CHECK (hash ~ '^[0-9a-f]{64}$'),
  at        timestamptz NOT NULL
);

-- Forward-looking: nothing in src/types.ts's Store interface queries by target today, but "show
-- the audit trail for message X" is an obvious future need (e.g. an audit-review console).
CREATE INDEX audit_log_target_idx ON audit_log (target);

REVOKE DELETE, UPDATE ON audit_log FROM PUBLIC;

CREATE OR REPLACE FUNCTION audit_log_block_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only: % is not permitted (id=%)', TG_OP, OLD.id;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_no_update
  BEFORE UPDATE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();

CREATE TRIGGER audit_log_no_delete
  BEFORE DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();

COMMIT;
